import type { Metadata } from 'next';
import { Source_Code_Pro } from 'next/font/google';
import './globals.css';
import { Header } from './Header';
const code = Source_Code_Pro({
  subsets: ['latin'],
  display: 'swap',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={code.className}>
        <main className="h-100 w-screen">
          <Header />
          <div className="w-1/2 mx-[25%] mt-[50px] text-primary">{children}</div>
        </main>
      </body>
    </html>
  );
}
